### ISSUE TITLE
Invert colors for active and inactive tabs on Firefox theme

### ISSUE THREAD

**Issue by Hedronmx** [dgsasha/dg-gnome-theme#1]
Hey! First of all, I LOVE THIS THEME! Its amazing!!

But i do believe that the firefox theme needs to invert the color of the active tab and inactive. On GNOME they always use light to show something is active, and grey to show that something is inactive.

Just my 2 cents.... The theme is just increidble! Thanks

**Comment by dgsasha** [comment]
The Firefox theme's tabs are based off the new libadwaita tab view. The colors are accurate.
