### ISSUE TITLE
[BUG] VS Code theme can not be selected

### ISSUE THREAD

**Issue by Simon-the-Sorcerer** [dgsasha/dg-gnome-theme#10]
**Describe the bug**
I have installed the VS code theme via `install.py`. After the installation the theme is not selectable in the list in VS code.

Furthermore the `settings.json` looks corrupt and is reported as error by code

```json
{
    "workbench.preferredDarkColorTheme": "qualia dark",
    "workbench.preferredLightColorTheme": "qualia light",
    "workbench.colorTheme": "qualia dark",
    "window.titleBarStyle": "custom",
    "window.menuBarVisibility": "toggle",
    "window.autoDetectColorScheme": true,
    "window.title": "${rootPath}${separator}Code",
    "breadcrumbs.enabled": false,
    "editor.renderLineHighlight": "none",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.tree.indent": 12,
        }
      },
    },
    },
    },
    },
        }
    },
    },
}
```

**To Reproduce**
1. Install theme via `install.py`
2. Open VS code
3. Press F1
4. Select Preferences: Color Theme
5. qualia theme is not in the list

**Expected behavior**
After the installation it should be possible to select the theme from the list.

**Screenshots/Log**
```
❯ ./install.py -s
Do you want to keep the default syntax highlighting in VS Code? [y/N]: 

The qualia GTK3 and Libadwaita GTK4 themes are up to date.
The qualia GNOME Shell, Xfwm4, Icon, Cursor, Sound, and GtkSourceView themes are up to date.
The qualia GTK4 configuration is up to date.
The qualia Firefox theme is up to date.
Installing the qualia VS Code theme in /home/simon/.vscode/extensions/qualia
Writing VS Code configuration to /home/simon/.config/Code/User/settings.json.
In VS Code, the menu bar will be hidden until you press 'alt'.
If you want to change this behavior, or any other settings, edit the 'settings.json' file.
Fehler beim Verbinden zur GNOME-Shell
'User Themes' GNOME Shell Extension not found, not enabling GNOME Shell theme.
Giving Flatpak apps access to the GTK themes.
Cleaning up...
Log out and log back in for everything to be updated.
```

![screenshot](https://user-images.githubusercontent.com/7312638/216926955-1d53339f-14c2-4bb2-8fbe-2987400d6fdf.png)

**Comment by emmi-ari** [comment]
Yeah the vscode theme installation just overwrites every user setting for vscode. That shouldn't happen.

**Comment by dgsasha** [comment]
I'll try to fix this soon. I'm working on something else atm and am busy with school so I haven't had much time to work on this project lately. For now just restore the backup settings file that was created.

**Comment by dgsasha** [comment]
@Simon-the-Sorcerer @Nihilopia Can you try the testing branch and see if all of your issues are fixed? Also check the README first because I added a dependency.
