### ISSUE TITLE
[BUG] Stop overwriting my vscode configuration

### ISSUE THREAD

**Issue by icebarf** [dgsasha/dg-gnome-theme#11]
Currently whenever I install the theme using `./install.py` for vscode, it overwrites the entire config without making any backup. I just lost my entire configuration.

**Comment by dgsasha** [comment]
Hi, I'm really sorry about this. It should be fixed now. There should have been a backup though, check for a file called settings.json.bak in ~/.config/Code/User

**Comment by icebarf** [comment]
Thank you dgsasha ❤️
