### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Hedronmx** [dgsasha/dg-gnome-theme#2]
I get the following error

```
ERROR: Destination '/usr/share/icons/dg-yaru/scalable/emblems/app-installed-symbolic.svg' already exists and is not a symlink
FAILED: meson-install 
```

**Comment by dgsasha** [comment]
Try running the uninstall script and then run the install script again. I'll look into what is causing the issue later.

**Comment by dgsasha** [comment]
This issue will be fixed once I roll out the next update to dg-gnome-theme, which should happen this weekend.
