### ISSUE TITLE
Theme don't work with firefox-gtk-theme

### ISSUE THREAD

**Issue by R34prZ** [dgsasha/dg-gnome-theme#4]
Just installed the theme and it looks great on all the apps i testes, but on firefox it don't apply the gtk4 gnome theme, as it's possible to see in your screenshots. Any idea on how to make it work?

**Comment by dgsasha** [comment]
Please provide more information. When running `./install.sh -r` does it ask to install the Firefox theme? If it does and you enter `y`, it's probably failing to install for some reason. Make sure you didnt have any other Firefox themes installed previously and if so, remove them.

**Comment by R34prZ** [comment]
I already had the firefox-gtk-theme installed, but i did uninstall it before. When i do `./install.sh -r` it says the firefox theme is already installed. The problem i had was: it installed the theme for firefox succesfully, but the desktop theme didn't apply (for example, title bar buttons stayed in the default gnome look); if i applied the dg-theme, the title bar was corrected, but the gtk-3-theme for firefox didn't work anymore (firefox turned to default theme)

**Comment by dgsasha** [comment]
A while ago I made some changes to the Firefox theme install script, but I forgot to say something here. Can you update and install the theme again and let me know if it's fixed? If it still doesn't work you could also try `./install.sh -r -f`, which will force reinstall all of the themes.

**Comment by R34prZ** [comment]
Now it works! Thanks.
