### ISSUE TITLE
[BUG] Theme does not install with the script

### ISSUE THREAD

**Issue by icebarf** [dgsasha/dg-gnome-theme#7]
**Describe the bug**
Running the install script should install the theme but instead the script just exits on VS Code theme part with no obvious indication. Using verbose mode yields no result, as is the same with force install mode.

**To Reproduce**
1. Follow the dependency and clone step
2. run `./install.py`
3. choose configuration

**Expected behavior**
Theme is successfully installed? I don't know, first time user and don't know what the expected behaviour is

**Screenshots/Log**
```
ice in ~/Git/qualia-gtk-theme on main λ ./install.py
Which accent color do you want?
  1:  Orange        2:  Bark
  3:  Sage          4:  Olive
  5:  Viridian      6:  Prussian Green
  7:  Light Blue    8:  Blue
  9:  Purple        10: Magenta
  11: Pink          12: Red
Enter the number corresponding to your choice [Default: 1]:
Which theme variant do you want?
  1:  Light         2:  Dark
  3:  Auto  (Only recommended for GNOME or Budgie)
Enter the number corresponding to your choice [Default: 1]:
Do you want to install the GTK3 theme? [Y/n]:
Do you want to install Libadwaita as a GTK4 theme? [Y/n]:
Do you want to install the custom GTK4 configuration? [Y/n]:
Do you want to install the GNOME Shell theme? [Y/n]:
Do you want to install the Icon theme? [Y/n]:
Do you want to install the Cursor theme? [Y/n]:
Do you want to install the Sound theme? [Y/n]:
Do you want to install the GtkSourceView theme? [Y/n]:
Do you want to install the Firefox theme? [Y/n]:
Do you want to theme the settings pages in Firefox? [Y/n]:
VS Code theme is not enabled, exiting.
```

**Additional context**
Gnome Shell Version: 43.2
Python Version: 3.10.8

**Comment by icebarf** [comment]
How I know the theme does not install:
1. Go to Gnome Tweaks application
2. Appearance
3. Check the `Shell`, `Icons`, `Cursor`, `Sound` sections
4. Found out there is nothing new in the lists

**Comment by dgsasha** [comment]
This should be fixed now, sorry about that.
