### ISSUE TITLE
[BUG] Uninstalling firefox theme also removes theme from `/usr/share`

### ISSUE THREAD

**Issue by icebarf** [dgsasha/dg-gnome-theme#8]
**Describe the bug**
Use the provided uninstall script to remove only the firefox theme, it also remove shell themes from `/usr/share` and thus making it unusable for the whole desktop environment

**To Reproduce**
1. Run the uninstall script as `./uninstall.py firefox`

**Expected behavior**
It only removes the theme from firefox.

**Screenshots/Log**
```
ice in ~/Git/qualia-gtk-theme on main λ ./uninstall.py firefox
Removing the Firefox theme.
```
**Additional context**
While the uninstall script removes the firefox theme which is the expected behavior. But it also uninstalls the gnome shell theme. I verified this from Gnome Tweaks application where in Appearance section, the Gnome Shell selection was empty and the list only contained default theme and my own themes. Qualia was removed.

**Comment by dgsasha** [comment]
Try updating the theme with `git pull`. I fixed this issue a few days ago. The uninstall script removes empty directories, and there was a bug that made it also remove the GNOME Shell theme.

**Comment by dgsasha** [comment]
Let me know if this is fixed so I can close it.

**Comment by icebarf** [comment]
Thanks, it's fixed.
