### ISSUE TITLE
[BUG] Transparency issues in Budgie 10.6.4

### ISSUE THREAD

**Issue by ghost** [dgsasha/dg-gnome-theme#9]
**Describe the bug**
This theme is awesome and very complete. However, the budgie styles have two small issues. 

1. If the panel transparency option is set to dynamic (when there's no fullscreen window) or "always" the panel becomes 100% transparent, making white icons invisible on a clear wallpaper.

2. The dialog menu when you press the power options in the budgie app menu and the user directories also don't have a proper background and are being drawn on top of the menu.

> As and additional note I got a gsettings error in the installation but the current theme did compile / install correctly.

**To Reproduce**
1. Just install the theme under Budgie 10.6.4~

**Expected behavior**
Correct transparency values?

**Screenshots/Log**

![Snapshot_2023-01-13_22-18-49](https://user-images.githubusercontent.com/24773698/212450437-7482724c-ac06-438b-9bde-1f946ff22a31.png)
![Snapshot_2023-01-13_22-19-40](https://user-images.githubusercontent.com/24773698/212450440-9c8e5ad5-4d13-40a6-b305-07ca0a95cde7.png)

**Additional context**
Id like to help if some guidance is provided :D I don't know much about CSS/SASS but I'm willing to cooperate or test in budgie if needed.

**Comment by dgsasha** [comment]
This menu is not actually a part of budgie by default, it's something that some distros add to it. I will try to fix this, but for now I would recommend adding the `budgie menu` and `user indicator` to the panel instead so you can have a usable app menu.

**Comment by dgsasha** [comment]
Ignore my last reply, I might have been wrong about this. I will have a fix uploaded soon.

**Comment by dgsasha** [comment]
It's fixed now. Also I'm happy to see someone using the budgie theme, so thanks!

**Comment by ghost** [comment]
I'll test the latest update and report anything I find! Thank you for your hard work on this :bow: , it's hard to find good GTK themes that work with Budgie.
